#!/usr/bin/env -S bash -e
# GMT modern mode bash template
# Date:    2021-03-02T22:31:25
# User:    pxlicumt
# Purpose: Purpose of this script
export GMT_SESSION_NAME=$$	# Set a unique session name
gmt begin figurename
	# Place modern session commands here
	gmt basemap -R10/70/-4/8 -JX8c/5c -Bxa10f5g10+l"X label" -Bya4f2g2+l"Y Label" -BWSen+t"Linear X-Y plot"
gmt end show
